Repository Bryson14/RubberDuckyParking, pull requests merged in 2021-02, with the labels that each got.

#6 Index page, base.html, and basic styling
  src/RubberDuckyParking/parking/templates/parking/about.html
  src/RubberDuckyParking/parking/templates/parking/host_index.html
  src/RubberDuckyParking/parking/templates/parking/index.html
  src/RubberDuckyParking/parking/urls.py
  src/RubberDuckyParking/parking/views.py
  src/RubberDuckyParking/static/css/styles.css
  src/RubberDuckyParking/static/favicon.ico
  src/RubberDuckyParking/templates/base.html
Labels: enhancement

#11 Index page
  src/RubberDuckyParking/parking/templates/parking/about.html
  src/RubberDuckyParking/parking/templates/parking/host_index.html
  src/RubberDuckyParking/parking/templates/parking/index.html
  src/RubberDuckyParking/static/css/styles.css
  src/RubberDuckyParking/templates/base.html
Labels: enhancement

#12 Use cases
  documentation/useCase PNGs/useCase1.png
  documentation/useCase PNGs/useCase2.png
  documentation/useCase PNGs/useCase3.png
  documentation/useCase PNGs/useCase4.png
  documentation/useCase PNGs/useCase5.png
  documentation/useCase PNGs/useCase6.png
  documentation/useCase PNGs/useCase7.png
  documentation/useCase PNGs/useCase8.png
  src/test2.txt
Labels: documentation

#13 made link to search page when they click the search button
  src/RubberDuckyParking/parking/templates/parking/index.html
  src/RubberDuckyParking/parking/templates/parking/search_reservation.html
  src/RubberDuckyParking/parking/views.py
  src/RubberDuckyParking/templates/base.html
Labels: enhancement

#18 Userdetails
  src/RubberDuckyParking/parking/templates/parking/user_details.html
  src/RubberDuckyParking/templates/base.html
  src/RubberDuckyParking/testLogo.png
  src/test2.txt
Labels: enhancement

#16 User routing
  src/RubberDuckyParking/RubberDuckyParking/urls.py
  src/RubberDuckyParking/parking/templates/parking/host_details.html
  src/RubberDuckyParking/parking/templates/parking/sign_up.html
  src/RubberDuckyParking/parking/templates/parking/user_details.html
  src/RubberDuckyParking/parking/urls.py
  src/RubberDuckyParking/parking/views.py
  src/RubberDuckyParking/parking_api/urls.py
  src/RubberDuckyParking/parking_api/views.py
  src/RubberDuckyParking/templates/base.html
Labels: bug

#20 changed all templates to Django templates that don't include the head …
  src/RubberDuckyParking/parking/templates/parking/attendant_details.html
  src/RubberDuckyParking/parking/templates/parking/index.html
  src/RubberDuckyParking/parking/templates/parking/login.html
  src/RubberDuckyParking/parking/templates/parking/parking_lot_tools.html
  src/RubberDuckyParking/parking/templates/parking/reservation_detail.html
  src/RubberDuckyParking/parking/templates/parking/user_details.html
  src/RubberDuckyParking/parking_api/urls.py
  src/RubberDuckyParking/static/testLogo.png
  src/RubberDuckyParking/templates/base.html
  src/RubberDuckyParking/templates/registration/login.html
Labels: bug
